name: MPUtils
version: ${project.version}
main: com.github.alfonsoleandro.mputils.MPUtils
api-version: "1.13"
authors: [lelesape]
description: Library for minecraft plugins development
website: https://bit.ly/2mwvHWN